# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pomo-ruby}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pedro Dias"]
  s.date = %q{2010-10-23}
  s.default_executable = %q{pomo-ruby}
  s.description = %q{Pomo-ruby is an standalone application written in Ruby/GTK with simple GUI to manage your time based on the Pomodoro technique.}
  s.email = %q{pedro.capaca@gmail.com}
  s.executables = ["pomo-ruby"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/pomo-ruby",
     "lib/core/cycle_runner.rb",
     "lib/core/input_validator.rb",
     "lib/core/timer.rb",
     "lib/gui/button_cancel.rb",
     "lib/gui/button_start.rb",
     "lib/gui/panel.rb",
     "lib/gui/progress_bar.rb",
     "lib/gui/text_field.rb",
     "lib/gui/window.rb",
     "lib/images/tomato.ico",
     "lib/images/tomato.jpg",
     "lib/images/tomato.png",
     "lib/pomo_ruby.rb",
     "pomo-ruby.gemspec"
  ]
  s.homepage = %q{http://github.com/capaca/pomo-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple application to run your Pomodoros in linux writen in GTK.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gtk2>, [">= 0.90.3"])
    else
      s.add_dependency(%q<gtk2>, [">= 0.90.3"])
    end
  else
    s.add_dependency(%q<gtk2>, [">= 0.90.3"])
  end
end

